//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarbaSoftware
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class bd_MarbaEntitiesCupomEntregas : DbContext
    {
        public bd_MarbaEntitiesCupomEntregas()
            : base("name=bd_MarbaEntitiesCupomEntregas")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<PreencherCupomEntregas_Result> PreencherCupomEntregas(string operador)
        {
            var operadorParameter = operador != null ?
                new ObjectParameter("operador", operador) :
                new ObjectParameter("operador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PreencherCupomEntregas_Result>("PreencherCupomEntregas", operadorParameter);
        }
    }
}
